/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreinscripcionRouteImport } from './routes/preinscripcion'
import { Route as PostulacionRouteImport } from './routes/postulacion'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedObrasSocialesIndexRouteImport } from './routes/_authenticated/obras-sociales/index'
import { Route as AuthenticatedMisHonorariosIndexRouteImport } from './routes/_authenticated/mis-honorarios/index'
import { Route as AuthenticatedLiquidacionesIndexRouteImport } from './routes/_authenticated/liquidaciones/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedEquipoIndexRouteImport } from './routes/_authenticated/equipo/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedBuzonIndexRouteImport } from './routes/_authenticated/buzon/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAlumnosIndexRouteImport } from './routes/_authenticated/alumnos/index'
import { Route as AuthenticatedAgendaIndexRouteImport } from './routes/_authenticated/agenda/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsInstitutionRouteImport } from './routes/_authenticated/settings/institution'
import { Route as AuthenticatedSettingsFinanceRouteImport } from './routes/_authenticated/settings/finance'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsClinicalRouteImport } from './routes/_authenticated/settings/clinical'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedAuditIntegrityRouteImport } from './routes/_authenticated/audit/integrity'
import { Route as AuthenticatedAlumnosIdRouteImport } from './routes/_authenticated/alumnos/$id'

const PreinscripcionRoute = PreinscripcionRouteImport.update({
  id: '/preinscripcion',
  path: '/preinscripcion',
  getParentRoute: () => rootRouteImport,
} as any)
const PostulacionRoute = PostulacionRouteImport.update({
  id: '/postulacion',
  path: '/postulacion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedObrasSocialesIndexRoute =
  AuthenticatedObrasSocialesIndexRouteImport.update({
    id: '/obras-sociales/',
    path: '/obras-sociales/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMisHonorariosIndexRoute =
  AuthenticatedMisHonorariosIndexRouteImport.update({
    id: '/mis-honorarios/',
    path: '/mis-honorarios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLiquidacionesIndexRoute =
  AuthenticatedLiquidacionesIndexRouteImport.update({
    id: '/liquidaciones/',
    path: '/liquidaciones/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipoIndexRoute =
  AuthenticatedEquipoIndexRouteImport.update({
    id: '/equipo/',
    path: '/equipo/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuzonIndexRoute = AuthenticatedBuzonIndexRouteImport.update({
  id: '/buzon/',
  path: '/buzon/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlumnosIndexRoute =
  AuthenticatedAlumnosIndexRouteImport.update({
    id: '/alumnos/',
    path: '/alumnos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgendaIndexRoute =
  AuthenticatedAgendaIndexRouteImport.update({
    id: '/agenda/',
    path: '/agenda/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsInstitutionRoute =
  AuthenticatedSettingsInstitutionRouteImport.update({
    id: '/institution',
    path: '/institution',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsFinanceRoute =
  AuthenticatedSettingsFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsClinicalRoute =
  AuthenticatedSettingsClinicalRouteImport.update({
    id: '/clinical',
    path: '/clinical',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditIntegrityRoute =
  AuthenticatedAuditIntegrityRouteImport.update({
    id: '/audit/integrity',
    path: '/audit/integrity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlumnosIdRoute = AuthenticatedAlumnosIdRouteImport.update({
  id: '/alumnos/$id',
  path: '/alumnos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/postulacion': typeof PostulacionRoute
  '/preinscripcion': typeof PreinscripcionRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/alumnos/$id': typeof AuthenticatedAlumnosIdRoute
  '/audit/integrity': typeof AuthenticatedAuditIntegrityRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/clinical': typeof AuthenticatedSettingsClinicalRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/finance': typeof AuthenticatedSettingsFinanceRoute
  '/settings/institution': typeof AuthenticatedSettingsInstitutionRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/agenda': typeof AuthenticatedAgendaIndexRoute
  '/alumnos': typeof AuthenticatedAlumnosIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/buzon': typeof AuthenticatedBuzonIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/equipo': typeof AuthenticatedEquipoIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/liquidaciones': typeof AuthenticatedLiquidacionesIndexRoute
  '/mis-honorarios': typeof AuthenticatedMisHonorariosIndexRoute
  '/obras-sociales': typeof AuthenticatedObrasSocialesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/postulacion': typeof PostulacionRoute
  '/preinscripcion': typeof PreinscripcionRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/alumnos/$id': typeof AuthenticatedAlumnosIdRoute
  '/audit/integrity': typeof AuthenticatedAuditIntegrityRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/clinical': typeof AuthenticatedSettingsClinicalRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/finance': typeof AuthenticatedSettingsFinanceRoute
  '/settings/institution': typeof AuthenticatedSettingsInstitutionRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/agenda': typeof AuthenticatedAgendaIndexRoute
  '/alumnos': typeof AuthenticatedAlumnosIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/buzon': typeof AuthenticatedBuzonIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/equipo': typeof AuthenticatedEquipoIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/liquidaciones': typeof AuthenticatedLiquidacionesIndexRoute
  '/mis-honorarios': typeof AuthenticatedMisHonorariosIndexRoute
  '/obras-sociales': typeof AuthenticatedObrasSocialesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/postulacion': typeof PostulacionRoute
  '/preinscripcion': typeof PreinscripcionRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/alumnos/$id': typeof AuthenticatedAlumnosIdRoute
  '/_authenticated/audit/integrity': typeof AuthenticatedAuditIntegrityRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/clinical': typeof AuthenticatedSettingsClinicalRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/finance': typeof AuthenticatedSettingsFinanceRoute
  '/_authenticated/settings/institution': typeof AuthenticatedSettingsInstitutionRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/agenda/': typeof AuthenticatedAgendaIndexRoute
  '/_authenticated/alumnos/': typeof AuthenticatedAlumnosIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/buzon/': typeof AuthenticatedBuzonIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/equipo/': typeof AuthenticatedEquipoIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/liquidaciones/': typeof AuthenticatedLiquidacionesIndexRoute
  '/_authenticated/mis-honorarios/': typeof AuthenticatedMisHonorariosIndexRoute
  '/_authenticated/obras-sociales/': typeof AuthenticatedObrasSocialesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/postulacion'
    | '/preinscripcion'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/alumnos/$id'
    | '/audit/integrity'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/clinical'
    | '/settings/display'
    | '/settings/finance'
    | '/settings/institution'
    | '/settings/notifications'
    | '/agenda'
    | '/alumnos'
    | '/apps'
    | '/buzon'
    | '/chats'
    | '/equipo'
    | '/help-center'
    | '/liquidaciones'
    | '/mis-honorarios'
    | '/obras-sociales'
    | '/settings/'
    | '/tasks'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/postulacion'
    | '/preinscripcion'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/alumnos/$id'
    | '/audit/integrity'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/clinical'
    | '/settings/display'
    | '/settings/finance'
    | '/settings/institution'
    | '/settings/notifications'
    | '/agenda'
    | '/alumnos'
    | '/apps'
    | '/buzon'
    | '/chats'
    | '/equipo'
    | '/help-center'
    | '/liquidaciones'
    | '/mis-honorarios'
    | '/obras-sociales'
    | '/settings'
    | '/tasks'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/postulacion'
    | '/preinscripcion'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/alumnos/$id'
    | '/_authenticated/audit/integrity'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/clinical'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/finance'
    | '/_authenticated/settings/institution'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/agenda/'
    | '/_authenticated/alumnos/'
    | '/_authenticated/apps/'
    | '/_authenticated/buzon/'
    | '/_authenticated/chats/'
    | '/_authenticated/equipo/'
    | '/_authenticated/help-center/'
    | '/_authenticated/liquidaciones/'
    | '/_authenticated/mis-honorarios/'
    | '/_authenticated/obras-sociales/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PostulacionRoute: typeof PostulacionRoute
  PreinscripcionRoute: typeof PreinscripcionRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preinscripcion': {
      id: '/preinscripcion'
      path: '/preinscripcion'
      fullPath: '/preinscripcion'
      preLoaderRoute: typeof PreinscripcionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postulacion': {
      id: '/postulacion'
      path: '/postulacion'
      fullPath: '/postulacion'
      preLoaderRoute: typeof PostulacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/obras-sociales/': {
      id: '/_authenticated/obras-sociales/'
      path: '/obras-sociales'
      fullPath: '/obras-sociales'
      preLoaderRoute: typeof AuthenticatedObrasSocialesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mis-honorarios/': {
      id: '/_authenticated/mis-honorarios/'
      path: '/mis-honorarios'
      fullPath: '/mis-honorarios'
      preLoaderRoute: typeof AuthenticatedMisHonorariosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/liquidaciones/': {
      id: '/_authenticated/liquidaciones/'
      path: '/liquidaciones'
      fullPath: '/liquidaciones'
      preLoaderRoute: typeof AuthenticatedLiquidacionesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipo/': {
      id: '/_authenticated/equipo/'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof AuthenticatedEquipoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buzon/': {
      id: '/_authenticated/buzon/'
      path: '/buzon'
      fullPath: '/buzon'
      preLoaderRoute: typeof AuthenticatedBuzonIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alumnos/': {
      id: '/_authenticated/alumnos/'
      path: '/alumnos'
      fullPath: '/alumnos'
      preLoaderRoute: typeof AuthenticatedAlumnosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda/': {
      id: '/_authenticated/agenda/'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/institution': {
      id: '/_authenticated/settings/institution'
      path: '/institution'
      fullPath: '/settings/institution'
      preLoaderRoute: typeof AuthenticatedSettingsInstitutionRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/finance': {
      id: '/_authenticated/settings/finance'
      path: '/finance'
      fullPath: '/settings/finance'
      preLoaderRoute: typeof AuthenticatedSettingsFinanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/clinical': {
      id: '/_authenticated/settings/clinical'
      path: '/clinical'
      fullPath: '/settings/clinical'
      preLoaderRoute: typeof AuthenticatedSettingsClinicalRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit/integrity': {
      id: '/_authenticated/audit/integrity'
      path: '/audit/integrity'
      fullPath: '/audit/integrity'
      preLoaderRoute: typeof AuthenticatedAuditIntegrityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alumnos/$id': {
      id: '/_authenticated/alumnos/$id'
      path: '/alumnos/$id'
      fullPath: '/alumnos/$id'
      preLoaderRoute: typeof AuthenticatedAlumnosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsClinicalRoute: typeof AuthenticatedSettingsClinicalRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsFinanceRoute: typeof AuthenticatedSettingsFinanceRoute
  AuthenticatedSettingsInstitutionRoute: typeof AuthenticatedSettingsInstitutionRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsClinicalRoute: AuthenticatedSettingsClinicalRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsFinanceRoute: AuthenticatedSettingsFinanceRoute,
    AuthenticatedSettingsInstitutionRoute:
      AuthenticatedSettingsInstitutionRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAlumnosIdRoute: typeof AuthenticatedAlumnosIdRoute
  AuthenticatedAuditIntegrityRoute: typeof AuthenticatedAuditIntegrityRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAgendaIndexRoute: typeof AuthenticatedAgendaIndexRoute
  AuthenticatedAlumnosIndexRoute: typeof AuthenticatedAlumnosIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedBuzonIndexRoute: typeof AuthenticatedBuzonIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedEquipoIndexRoute: typeof AuthenticatedEquipoIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedLiquidacionesIndexRoute: typeof AuthenticatedLiquidacionesIndexRoute
  AuthenticatedMisHonorariosIndexRoute: typeof AuthenticatedMisHonorariosIndexRoute
  AuthenticatedObrasSocialesIndexRoute: typeof AuthenticatedObrasSocialesIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAlumnosIdRoute: AuthenticatedAlumnosIdRoute,
  AuthenticatedAuditIntegrityRoute: AuthenticatedAuditIntegrityRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAgendaIndexRoute: AuthenticatedAgendaIndexRoute,
  AuthenticatedAlumnosIndexRoute: AuthenticatedAlumnosIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedBuzonIndexRoute: AuthenticatedBuzonIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedEquipoIndexRoute: AuthenticatedEquipoIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedLiquidacionesIndexRoute: AuthenticatedLiquidacionesIndexRoute,
  AuthenticatedMisHonorariosIndexRoute: AuthenticatedMisHonorariosIndexRoute,
  AuthenticatedObrasSocialesIndexRoute: AuthenticatedObrasSocialesIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PostulacionRoute: PostulacionRoute,
  PreinscripcionRoute: PreinscripcionRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
